# Generated by Django 4.2 on 2023-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carouselmodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_type', models.CharField(blank=True, choices=[('физическим лицам', 'Физическим лицам'), ('юридическим лицам', 'Юридическим лицам')], default=('физическим лицам', 'Физическим лицам'), max_length=70, null=True, verbose_name='borrower_type')),
                ('loan_amount', models.FloatField(verbose_name='loan_amount')),
                ('loan_term', models.IntegerField(verbose_name='loan_term')),
                ('interest_rate', models.FloatField(verbose_name='interest_rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Calculator',
                'verbose_name_plural': 'Calculators',
            },
        ),
    ]
