# Generated by Django 4.2 on 2023-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_whosecreditmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCreditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=400, verbose_name='subtitle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'What documents are needed?',
                'verbose_name_plural': 'What documents are needed',
            },
        ),
        migrations.AlterField(
            model_name='whosecreditmodel',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='title'),
        ),
    ]
