# Generated by Django 4.2 on 2023-04-15 17:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_individualcredittypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('short_description', models.TextField(verbose_name='description')),
                ('long_description', ckeditor.fields.RichTextField(verbose_name='long_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Legal Entities',
                'verbose_name_plural': 'Legal Entities',
            },
        ),
    ]
