# Generated by Django 4.2 on 2023-04-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_faqmodel_description_ru_faqmodel_description_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_type', models.CharField(max_length=20)),
                ('loan_period', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
            },
        ),
        migrations.DeleteModel(
            name='CalculatorModel',
        ),
    ]
