# Generated by Django 4.2 on 2023-04-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_loan_options_alter_loan_loan_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('principal_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
