# Generated by Django 4.2 on 2023-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_credit_payment_delete_loan_delete_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='overpayment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='credit',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='credit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
