# Generated by Django 4.2 on 2023-04-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_credit_overpayment_credit_total_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='overpayment',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='total_payments',
        ),
    ]
