# Generated by Django 4.2 on 2023-04-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_credit_overpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentitiesmodel',
            name='first_image',
            field=models.FileField(default=1, upload_to='Individual-images', verbose_name='first_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalentitiesmodel',
            name='second_image',
            field=models.FileField(default=1, upload_to='Individual-images', verbose_name='second_image'),
            preserve_default=False,
        ),
    ]
