# Generated by Django 4.2 on 2023-05-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_credit_payment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselmodel',
            name='link',
        ),
    ]
