# Generated by Django 4.2 on 2023-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_carouselmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
