# Generated by Django 4.2 on 2023-09-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_japanesecarouselmodel_descriptions_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='japanesecarouselmodel',
            name='descriptions_ru',
        ),
        migrations.RemoveField(
            model_name='japanesecarouselmodel',
            name='descriptions_uz',
        ),
        migrations.RemoveField(
            model_name='japanesecarouselmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='japanesecarouselmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='japaneseproductmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='japaneseproductmodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='japaneseproductmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='japaneseproductmodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='japaneseteammodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='japaneseteammodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='japaneseteammodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='japaneseteammodel',
            name='name_uz',
        ),
    ]
